# Your Solution
version: '3'
services:
  book_catalog:
    image: book_catalog:v1
    build: 
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book_catalog
    environment:
      - PORT=7000
      - DATABASE_URL=postgresql://purva_sit722_part5_user:8cpw5oglNjInCjUpEgwDWoLezynBQm5j@dpg-crnb28u8ii6s73enq9sg-a.oregon-postgres.render.com/purva_sit722_part5

  inventory_management:
    image: inventory_management:v1
    build: 
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory_management
    environment:
      - PORT=7001
      - DATABASE_URL=postgresql://purva_sit722_part5_user:8cpw5oglNjInCjUpEgwDWoLezynBQm5j@dpg-crnb28u8ii6s73enq9sg-a.oregon-postgres.render.com/purva_sit722_part5