# Your Solution
version: '3'
services:
  book_catalog:
    image: ${CONTAINER_REGISTRY}.azurecr.io/book_catalog:${VERSION}
    build: 
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book_catalog
    environment:
      - PORT=7000
      - DATABASE_URL=postgresql://purva_sit722_part5_8v4f_user:EzzOiOHMkcOt2hFps39hnl1dWrcGDTcp@dpg-crvr3ma3esus7395oid0-a.oregon-postgres.render.com/purva_sit722_part5_8v4f

  inventory_management:
    image: ${CONTAINER_REGISTRY}.azurecr.io/inventory_management:${VERSION}
    build: 
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory_management
    environment:
      - PORT=7001
      - DATABASE_URL=postgresql://purva_sit722_part5_8v4f_user:EzzOiOHMkcOt2hFps39hnl1dWrcGDTcp@dpg-crvr3ma3esus7395oid0-a.oregon-postgres.render.com/purva_sit722_part5_8v4f