name: Deploy Gateway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      VERSION: ${{ github.sha }}
      CONTAINER_REGISTRY: crpart5.azurecr.io
      REGISTRY_UN: ${{ secrets.REGISTRY_UN }} # Store this in GitHub Secrets
      REGISTRY_PW: ${{ secrets.REGISTRY_PW }} # Store this in GitHub Secrets
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      NAME: gateway
      DIRECTORY: gateway

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Log in to Azure Container Registry without interactive prompts
      - name: Log in to Azure Container Registry
        run: |
          docker login ${{ env.CONTAINER_REGISTRY }} \
            --username ${{ env.REGISTRY_UN }} \
            --password ${{ env.REGISTRY_PW }}

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t "${{ env.CONTAINER_REGISTRY }}/${{ env.NAME }}:${{ env.VERSION }}" ${{ env.DIRECTORY }}

      # Push Docker image to the Azure Container Registry
      - name: Push Docker image
        run: |
          docker push "${{ env.CONTAINER_REGISTRY }}/${{ env.NAME }}:${{ env.VERSION }}"

      # Additional deployment steps (e.g., deploying to Kubernetes) can go here
