name: Deploy Book Catalog and Inventory Management Services

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows triggering manually

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Azure Login
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve

      - name: Get Container Registry Name
        working-directory: ./terraform
        run: |
          echo "Registry name output:"
          terraform output -raw registry_name
          CONTAINER_REGISTRY=$(terraform output -raw registry_name)
          echo "CONTAINER_REGISTRY=${CONTAINER_REGISTRY}" >> $GITHUB_ENV



      - name: Login to Azure Container Registry
        run: |
          echo ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }} | docker login ${{ env.CONTAINER_REGISTRY }}.azurecr.io -u ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }} --password-stdin

      # Set permissions for build, push, deploy scripts
      - name: Set permissions for build, push, deploy scripts
        working-directory: ./scripts/
        run: |
          chmod +x build-image.sh
          chmod +x push-image.sh
          chmod +x deploy.sh
          chmod +x delete.sh

      - name: Docker Images
        env:
          CONTAINER_REGISTRY: ${{ env.CONTAINER_REGISTRY }}
          VERSION: ${{ github.sha }}
        run: ./build-image.sh

      - name: Push Images
        env:
          CONTAINER_REGISTRY: ${{ env.CONTAINER_REGISTRY }}
          VERSION: ${{ github.sha }}
        run: ./push-image.sh

   
