name: Deploy Book Catalog and Inventory Management Services

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      VERSION: ${{ github.sha }}
      CONTAINER_REGISTRY: crpart5.azurecr.io
      REGISTRY_UN: ${{ secrets.REGISTRY_UN }}
      REGISTRY_PW: ${{ secrets.REGISTRY_PW }}
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      BOOK_CATALOG_DIR: book_catalog         # Directory for book_catalog service
      INVENTORY_MANAGEMENT_DIR: inventory_management  # Directory for inventory_management service

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Log in to Azure Container Registry
      - name: Log in to Azure Container Registry
        run: |
          docker login ${{ env.CONTAINER_REGISTRY }} \
            --username ${{ env.REGISTRY_UN }} \
            --password ${{ env.REGISTRY_PW }}

      # Build Book Catalog Docker image
      - name: Build Book Catalog Docker image
        run: |
          docker build -t "${{ env.CONTAINER_REGISTRY }}/book_catalog:${{ env.VERSION }}" ${{ env.BOOK_CATALOG_DIR }}

      # Push Book Catalog Docker image
      - name: Push Book Catalog Docker image
        run: |
          docker push "${{ env.CONTAINER_REGISTRY }}/book_catalog:${{ env.VERSION }}"

      # Build Inventory Management Docker image
      - name: Build Inventory Management Docker image
        run: |
          docker build -t "${{ env.CONTAINER_REGISTRY }}/inventory_management:${{ env.VERSION }}" ${{ env.INVENTORY_MANAGEMENT_DIR }}

      # Push Inventory Management Docker image
      - name: Push Inventory Management Docker image
        run: |
          docker push "${{ env.CONTAINER_REGISTRY }}/inventory_management:${{ env.VERSION }}"
