name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Change this to your default branch if necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.ACR_NAME }}.azurecr.io
        username: ${{ secrets.ACR_NAME }}
        password: ${{ secrets.AZURE_CLIENT_SECRET }}

    - name: Build and push Docker images
      run: |
        # Build and push the book_catalog image
        docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/book_catalog:latest ./book_catalog
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/book_catalog:latest

        # Build and push the inventory_management image
        docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/inventory_management:latest ./inventory_management
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/inventory_management:latest

    - name: Set up Azure CLI
      uses: azure/setup-azure@v1
      with:
        azure_subscription: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        azure_service_principal: ${{ secrets.AZURE_CLIENT_ID }}
        azure_service_principal_password: ${{ secrets.AZURE_CLIENT_SECRET }}
        azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}

    - name: Update Kubernetes deployment
      run: |
        az aks get-credentials --resource-group ${{ secrets.RESOURCE_GROUP }} --name ${{ secrets.K8S_CLUSTER_NAME }}
        kubectl apply -f scripts/kubernetes/deployment.yaml
