name: Deploy Book Catalog and Inventory Management Services

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      #Azure
     - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      #Terraform     
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: terraform init
        working-directory: ./terraform
        run: terraform init

      - name: terraform plan
        working-directory: ./terraform
        run: terraform plan

      - name: terraform apply
        working-directory: ./terraform
        run: terraform apply -auto-approve

      - name: Get Container Registry Name
        working-directory: ./terraform
        run: |
          CONTAINER_REGISTRY=$(terraform-bin output -raw registry_name)
          echo "CONTAINER_REGISTRY=$CONTAINER_REGISTRY" >> $GITHUB_ENV
          
      - name: Login to Azure Container Registry
        run: |
          echo ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }} | docker login ${{ env.CONTAINER_REGISTRY }}.azurecr.io -u ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }} --password-stdin

       #Docker image
      - name: Set permissions for build, push, deploy scripts
        working-directory: ./scripts/
        run: |
          chmod +x build-image.sh
          chmod +x push-image.sh
          chmod +x deploy.sh
          chmod +x delete.sh

      - name: Docker images
        env:
          CONTAINER_REGISTRY: ${{ env.CONTAINER_REGISTRY }}
          VERSION: ${{ github.sha }}
        run: ./build-image.sh


      - name: Push images
        env:
          CONTAINER_REGISTRY: ${{ env.CONTAINER_REGISTRY }}
          VERSION: ${{ github.sha }}
        run: ./push-image.sh

      #Kubernetes
      - name: Kubernetes Config
        working-directory: ./scripts/terraform
        run: |
          KUBECONFIG_CONTENT=$(terraform-bin output -raw kube_config)
          echo "KUBECONFIG_CONTENT=$KUBECONFIG_CONTENT" >> $GITHUB_ENV

      - name: Set up kubectl
        uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ env.KUBECONFIG_CONTENT }}
          kubectl-version: v1.30.3

      - name: Deploy images
        env:
          CONTAINER_REGISTRY: ${{ env.CONTAINER_REGISTRY }}
          VERSION: ${{ github.sha }}
        run: ./deploy.sh

      