name: Deploy Gateway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      VERSION: ${{ github.sha }}
      CONTAINER_REGISTRY: crpart5.azurecr.io
      REGISTRY_UN: CRpart5
      REGISTRY_PW: ${{ secrets.AZURE_CLIENT_SECRET }}
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      NAME: gateway
      DIRECTORY: gateway

    steps:
      # Checks out your repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Log in to Azure Container Registry
      - name: Log in to Azure Container Registry
        run: |
          echo "${{ secrets.AZURE_CLIENT_SECRET }}" | docker login "${{ env.CONTAINER_REGISTRY }}" --username "${{ env.REGISTRY_UN }}" --password-stdin

      # Add your build, deploy, or other steps here
      # For example, building the Docker image
      - name: Build Docker image
        run: |
          docker build -t "${{ env.CONTAINER_REGISTRY }}/${{ env.NAME }}:${{ env.VERSION }}" ${{ env.DIRECTORY }}

      # Push the Docker image to the Azure Container Registry
      - name: Push Docker image
        run: |
          docker push "${{ env.CONTAINER_REGISTRY }}/${{ env.NAME }}:${{ env.VERSION }}"
          
      # Add any additional deployment steps here
