jobs:

  deploy:
    runs-on: ubuntu-latest
    
    env:
      VERSION: ${{ github.sha }}
      CONTAINER_REGISTRY: ${{ secrets.ACR_NAME }}.azurecr.io
      REGISTRY_UN: ${{ secrets.ACR_NAME }}
      REGISTRY_PW: ${{ secrets.AZURE_CLIENT_SECRET }}
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

    steps:
      
      # Checks out your repository
      - uses: actions/checkout@v3

      #
      # Logs in to Azure Container Registry.
      #
      - name: Log in to Azure Container Registry
        run: |
          echo "${{ secrets.AZURE_CLIENT_SECRET }}" | docker login "${{ secrets.ACR_NAME }}.azurecr.io" --username "${{ secrets.ACR_NAME }}" --password-stdin
